version: '3'
services:
  mysql:
    image: mysql
    networks: 
      - production-network
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: lucas
    ports:
      - "3306:3306"
      
  api-antfy:
    build: 
      dockerfile: ./antfy_backend/antfy.dockerfile
      context: .
    image: lulukc/api-antfy
    container_name: antfy
    ports:
      - "8080:8080"
    networks: 
      - production-network
    depends_on: 
      - mysql
      - api-sintomas

  mongodb:
    image: mongo
    networks: 
      - production-network
    ports:
      - "27017:27017"

  api-sintomas:
    build: 
      dockerfile: ./api-sintomas/sintomas.dockerfile
      context: .
    image: lulukc/api-sintomas
    ports:
      - "3333:3333"
    networks: 
      - production-network
    depends_on: 
      - mongodb

networks: 
  production-network:
    driver: bridge